# Site settings
title: netbuk.blog
email: blog(at)etbuk.de
description: > # this means to ignore newlines until "baseurl:"
  This blog is proudly powered by GitHub.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://netbuk.github.io" # the base hostname & protocol for your site
twitter_username: der__k
github_username:  netbuk

# Build settings
markdown: kramdown
