#
###################################
# Site wide configuration
####################################
#
title: netbuk.blog
email: christian@netbuk.de
description: > # this means to ignore newlines until "baseurl:"
  kleiner privater technik blog.
url: http://netbuk.github.io/ # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter: pygments
excerpt_separator: <!--more-->
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

#
###################################
# Jekyll configuration
####################################
#
owner:
  name: Christian
  avatar: bio-photo.jpg
  bio: "Work hard, play harder."
  email: christian@netbuk.de
  disqus-shortname: netbuk.dk
  twitter: der__k #username
  facebook: christian.kantelberg #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: netbuk #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: der.k #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
